VnnewsNews/Controllers/TakePriceController.cs
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VnnewsNews.Function;

namespace VnnewsNews.Controllers
{
    public class TakePriceController : Controller
    {
        Model.EF.DBvnewsEntities db = new Model.EF.DBvnewsEntities();
        FunctionsController func = new FunctionsController();
        // GET: TakePrice
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetMoney()
        {
            if(func.CookieID() == null)
            {
                return Redirect("/Account/Login");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetMoney(TakePrice takePrice)
        {
            if (ModelState.IsValid)
            {
                takePrice.tp_datecreate = DateTime.Now;
                takePrice.tp_active = false;
                takePrice.user_id = func.CookieID().user_id;
                db.TakePrices.Add(takePrice);
                db.SaveChanges();
                TempData["noti_takeprice"] = "Yeu cau cua ban da duoc gui vui long doi!";
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

VnnewsNews/Views/TakePrice/GetMoney.cshtml
@{
    VnnewsNews.Function.FunctionsController func = new VnnewsNews.Function.FunctionsController();
    ViewBag.Title = "GetMoney";
}

<h2>GetMoney</h2>


<form action="@Url.Action("GetMoney", "TakePrice")" method="post">
    @Html.AntiForgeryToken()
    <input type="text" name="tp_totalmoney" class="form-control"/>
    <input type="text" value="@func.CookieID().user_name" class="form-control" readonly/>
    <input type="text" value="@func.CookieID().user_phone" class="form-control" readonly/>
    <input type="submit" value="Rut tien" />
</form>

VnnewsNews/Views/TakePrice/Index.cshtml
@{
    ViewBag.Title = "NewsFavorite";
}

<h2>NewsFavorite <a href="/TakePrice/GetMoney">Rut Tien</a></h2>
<span>@TempData["noti_takeprice"]</span>

<div ng-app="myApp">
    <div ng-controller="myCtrl">
        <table>
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Money</th>
                    <th>Phone</th>
                    <th>Customs</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="list in list">
                    <td>{{$index + 1}}</td>
                    <td>{{list.money}}</td>
                    <td>{{list.phone}}</td>
                    <td>
                        <a href="/News/Details?id={{list.news_id}}" target="_blank"><span>Xem</span></a>
                        <a href="" ng-click="remove($index, list.id)"><span>Xoa</span></a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<!-- angular -->
<script>
    var app = angular.module('myApp', []);
    app.controller('myCtrl', function ($scope, $http) {
        $http({
            method: "GET",
            url: "/Json/GetHistoryTakePrice"
        }).then(function mySuccess(response) {
            $scope.list = response.data;
            $scope.remove = function (item, id) {
                var index = $scope.list.indexOf(item);
                $scope.list.splice(index, 1);
                $http.get('/Json/RemoveHistoryTakePrice?id=' + id).success(function (data) {
                    $scope.title = data;
                })
            }
        }, function myError(response) {
            $scope.list = response.statusText;
        })
    });

</script>